template = ""
rev_id = 5
template_sha = "b1bcc12f5675c5b86f53da0a290c53417f28d6e3"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "et"
__UND2C_TRG__ = "nb"
__UNDEFINED_SOURCE__ = "Estonian"
__UNDEFINED_TARGET__ = "Norwegian Bokmål"
__UND_SRC__ = "est"
__UND_TRG__ = "nob"
